# Generated by Django 4.2.7 on 2023-11-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='job_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cities'),
        ),
    ]
