# Generated by Django 4.2.7 on 2023-11-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('organizations', '0002_alter_organizations_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.cities'),
        ),
    ]
